name: Development/Heroku
on:
  push:
    branches:
      - staging
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install all dependecies
        run: npm install
      # - name: Run the tests and generate coverage report
      #   run: npm run coverage

  deploy:
    # Avoid conflicts btn different jobs (group workflows having the name of "heroku_deployment")
    concurrency:
      group: heroku_deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'keza-staging-weather'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
